GoogleCloudPlatform/cloud-bigtable-examples

java/managed-vms/README.md
java/managed-vms/helloworld/pom.xml
java/managed-vms/helloworld/src/main/webapp/WEB-INF/appengine-web.xml

1. No longer need rolled back cloud command
2. Fix README
3. Latest mvn gcloud tool
4. Stupid error in pom.xml - fixed.

Back to cloud latest, fix README, error in POM

---

java/managed-vms/README.md
java/managed-vms/helloworld/pom.xml
java/managed-vms/helloworld/src/main/java/com.example.cloud.bigtable.helloworld/BigtableHelper.java
java/managed-vms/helloworld/src/main/webapp/Dockerfile
java/managed-vms/helloworld/src/main/webapp/WEB-INF/appengine-web.xml
java/managed-vms/helloworld/src/main/webapp/WEB-INF/web.xml

1. Instead of setting project_ID & version in the pom.xml, let gcloud do it
2. Fix package names in web.xml (My Bad .. some files didn’t get copied)
3. Get rid of projectID & version from appengine-web.xml
4. Get rid of old comment and set target utilization to 0.5 - another
change that didn’t get migrated.
5. Add comment for GOOGLE_APPLICATION_CREDENTIALS
6. Add set_default key to mvn

More updates per Ludo and fixing my stupidity.

---

java/jetty-managed-vm/bigtable-hello/src/main/java/com/example/cloud/bigtable/helloworld/BigtableHelper.java
java/managed-vm-gae/gae-bigtable-hello/src/main/java/com/example/cloud/bigtable/helloworld/BigtableHelper.java
java/simple-cli/README.md
java/simple-cli/src/main/resources/hbase-site.xml
java/storm/README.md
java/storm/src/main/resources/hbase-site.xml
quickstart/create-hbase-site

The config properties `google.bigtable.endpoint.host` and `google.bigtable.admin.endpoint.host` are now automatically set by default, so it should be safe to remove them from the code samples.
This pull request supersedes #54.

Remove obsolete configuration properties

---

java/simple-cli/README.md

This info currently lives in the [cloud.google.com docs](https://cloud.google.com/bigtable/docs/samples-simple-cli). I'm planning to remove it from there, in accordance with our new rules for documenting code samples.

Correct the syntax for the `scan` command, and add docs for filter expressions

---

python/rest/README.md

These edits make the `README` a bit easier to follow. They also include a few helpful changes, such as running the REST server in the background.
You can [preview the updated `README` on my branch](https://github.com/hegemonic/cloud-bigtable-examples/tree/python-rest-readme/python/rest).

Improve the README for the Python REST example

---

python/thrift/provision.sh

I haven't tested this fix, but it seems pretty obviously correct. (Right now we're downloading one version of a .deb file, then trying to install a different version.)
1.14.1-3 is the version number we want according to the [Thrift installation docs for Debian](https://thrift.apache.org/docs/install/debian).

Fix typo in Thrift provisioning script

---

java/managed-vm-gae/src/main/webapp/Dockerfile

The remote builds sometimes have some connectivity
issues.

Switch ALPN Jars to GCS

---

java/dataflow-connector-examples/README.md

Tried to test this out. It seems we should always do "mvn package" (or compile) first, otherwise the main class will be missing.

Do mvn package before exec:exec

---

java/dataflow-coinbase/dataflow/README.md
java/dataflow-coinbase/frontend/README.md

For now, just tell people you can't run locally. I will look into whether it makes more sense to hold off for MVM working for this case, or switch to GCE.

Remove local instructions

---

java/wordcount-mapreduce/README.md
java/wordcount-mapreduce/dp-mr-hb-init.sh
java/wordcount-mapreduce/pom.xml
java/wordcount-mapreduce/src/main/resources/hbase-site.xml

No longer required - clusters have Cloud Bigtable enabled by default
now.

Remove the key.json file

---

quickstart/pom.xml

The Cloud Shell can't allocate 1G to the quickstart.  256M is enough for a good start.

Use 256M as minimum in quickstart

---

quickstart/thirdparty/ruby/hbase/admin.rb

The quickstart fails to 'list' on go generated tables.  Using listTableNames() instead of listTables() corrects that problem and is more efficient to boot.

Updating admin.rb

---

quickstart/pom.xml

We need a bit more memory now that we use BoringSSL -- Fixes hang on Cloud Shell
@sduskis FYI

Increase quick start size

---

python/thrift/appengine-ssl-gateway/README.md
python/thrift/appengine-ssl-gateway/appengine/.gitignore
python/thrift/appengine-ssl-gateway/appengine/Makefile
python/thrift/appengine-ssl-gateway/appengine/app.yaml
python/thrift/appengine-ssl-gateway/appengine/appengine_config.py
python/thrift/appengine-ssl-gateway/appengine/bigtable.py
python/thrift/appengine-ssl-gateway/appengine/requirements.txt
python/thrift/appengine-ssl-gateway/appengine/web/create.jinja
python/thrift/appengine-ssl-gateway/appengine/web/delete.jinja
python/thrift/appengine-ssl-gateway/appengine/web/index.jinja
python/thrift/appengine-ssl-gateway/common.mk
python/thrift/appengine-ssl-gateway/thrift-gateway/.gitignore
python/thrift/appengine-ssl-gateway/thrift-gateway/Dockerfile
python/thrift/appengine-ssl-gateway/thrift-gateway/Makefile
python/thrift/appengine-ssl-gateway/thrift-gateway/deployment.jinja
python/thrift/appengine-ssl-gateway/thrift-gateway/deployment.yaml
python/thrift/appengine-ssl-gateway/thrift-gateway/install-hbase.sh
python/thrift/appengine-ssl-gateway/thrift-gateway/start-thrift.sh

This howto provides instructions for creating an App Engine app which will
connect to a load-balanced, autoscaled managed instance group of HBase Thrift
gateways which will connect to Cloud Bigtable.
Many thanks to Ben Menasha for the initial version of these instructions.
@bmenasha, @lesv — please review and comment.

App Engine - SSL - Thrift Gateway - Cloud Bigtable

---

python/thrift/appengine-ssl-gateway/thrift-gateway/Makefile

Do not rely on gcloud config value, which may refer to an unrelated project.
Since we already have the `$PROJECT_ID` env var, let's use it here as well.

Set project id explicitly for gcloud via env var.

---

java/dataflow-coinbase/dataflow/pom.xml
java/dataflow-coinbase/pom.xml
java/dataflow-connector-examples/pom.xml
java/dataflow-import-examples/pom.xml
java/dataflow-pardo-helloworld/pom.xml
java/hello-world/pom.xml
java/managed-vm-gae/pom.xml
java/simple-cli/hbasecli.sh
java/simple-cli/pom.xml
java/simple-performance-test/pom.xml
java/wordcount-mapreduce/README.md
java/wordcount-mapreduce/bigtable-dataproc-init.sh
java/wordcount-mapreduce/cluster.sh
java/wordcount-mapreduce/pom.xml
quickstart/pom.xml

1. In most pom’s, add the sonatype snapshot repo. remove -Pstaged option. -Dbigtable.version=0.2.4-SNAPSHOT should work now w/o help.
2. In most pom’s add the Google-Maven-Central mirror
3. Dataproc is GA
4. Dataproc includes alpa-boot on the run line by default
5. Made simple-cli use boring-ssl, much faster.
6. Update to latest GAE / gcloud
Note - I left some data flow examples using alpa-boot as there are some
issues w/ boring-ssl and Docker containers. (Docker doesn’t like IPv6)
@sduskis @hegemonic @IanLewis @mbrukman FYI

Update to client 0.2.4

---

java/dataflow-pardo-helloworld/pom.xml
java/hello-world/pom.xml
java/pom.xml
java/simple-cli/pom.xml
java/simple-performance-test/pom.xml

1. Where possible update HBase to 1.2.1
2. These 4 are tested.
3. gae-flex the gcloud mvm plugin appears to have regressed, so I’m not
yet updating
4. Dataproc-wordcount needs some work
5. dataflow-connector ran into an issue and I’m debugging, a new PR for
that.
dataflow-pardo-helloworld, hello-world, simple-cli, and
simple-performance have been tested and passed.

Update Client to 0.3.0

---

python/rest/.gitignore
python/rest/README.md
python/rest/put_get.py
python/rest/put_get_with_client.py
python/rest/requirements.txt
python/rest/rest_client.py

This is one of the steps in getting ready to enable automated tests for the Python samples.
I will have a similar PR for the thrift directory, but I haven't had time to manually test that code yet.

Fix flake8 errors in Python REST sample.

---

python/thrift/client.py
python/thrift/flask_thrift.py
python/thrift/requirements.txt
python/thrift/test.py

I manually tested these on a new GCE instance. Note: The readme claims
the Thrift sample only works on GCE so I did not try to test on my
workstation.

Fix flake8 errors in Python Thrift sample.

---

java/dataproc-wordcount/pom.xml
quickstart/pom.xml
quickstart/quickstart.sh

1. Disambiguation for Clusters & Projects
2. Use exec:java to use less memory.  Fixes issue on DevShell hanging, I'm not
releasing as there are scary errors on exit
3. dataproc-wordcount/pom no longer needs to know a cluster name.
@sduskis @hegemonic FYI

Update QuickStart to use mvm:java and disambiguate

---

java/dataproc-wordcount/pom.xml

- Explicitely excluding the bigtable-hbase-1.1 dependency from the
bigtable-hbase-mapreduce include.
- Adding an explicit dependency on the correct hbase-server version
- Moving up the hbase-client dependency.

Updating the wordcount pom.xml

---

java/hello-world/src/main/java/com/example/cloud/bigtable/helloworld/HelloWorld.java

Using sequential keys should be discouraged, as this really limits
Bigtable write performance. It's not any more complex to use a UUID, so
I think we should have our hello world example use those instead.
See: https://cloud.google.com/bigtable/docs/schema-design
PTAL @lesv

Add disclaimer about schema design to Java Hello World.

---

README.md
java/dataflow-connector-examples/pom.xml
java/dataflow-import-examples/pom.xml
java/dataflow-pardo-helloworld/README.md
java/dataflow-pardo-helloworld/pom.xml
java/dataproc-wordcount/pom.xml
java/gae-flexible-helloworld/README.md
java/gae-flexible-helloworld/pom.xml
java/hello-world/README.md
java/hello-world/pom.xml
java/simple-cli/pom.xml
java/simple-performance-test/pom.xml
quickstart/README.md
quickstart/pom.xml

1. Samples now use netty tcnative-boringssl-static Fork19 ‘UberJar’
2. UberJar means that we don’t need to figure out which tcnative to use.
3. pom’s and README’s got a bit simpler.
4. An error in the dataflow-partdo-helloworld README.md was fixed.

Update client to 0.9.1

---

java/dataflow-import-examples/pom.xml

This matches the variables that are expected in the exec plugin definition.

Rename cluster property to instanceID.

---

python/thrift/client.py
python/thrift/requirements.txt

New version of flake8 needs the imports below the path addition to also
have a comment to ignore them for the linter.
@lesv PTAL. This should make Travis happy.

Fix lint errors and updated requirements.

---

java/dataflow-connector-examples/pom.xml
java/dataflow-import-examples/pom.xml
java/dataproc-wordcount/pom.xml
java/hello-world/pom.xml
java/simple-cli/pom.xml
java/simple-performance-test/pom.xml
quickstart/pom.xml

0.9.3 had major problems due to a netty bug.  0.9.4 fixes that plus a whole bunch of other things.

Updating to cloud bigtable client 0.9.4.

---

python/thrift/flask_thrift.py
travis.sh

Two problems were preventing the Travis build from passing:
1. An update in flake8 caught an issue where we weren't separating top-level definitions by two newlines.
2. The Oracle Java installer stalled waiting for confirmation on overwriting a configuration file.
This PR should fix both issues.
@lesv PTAL

Fix the Travis build configuration.

---

java/hello-world/README.md

The README makes it sound like `gcloud auth application-default login` can be replaced by gcloud login, however
generating a `application_default_credentials.json` will still be needed. This change will handle that bit of setup for the user.

Update java hello README to include required step

---

java/pom.xml
java/tracing-hello-world/README.md
java/tracing-hello-world/pom.xml
java/tracing-hello-world/src/main/java/com/example/cloud/bigtable/helloworld/HelloWorld.java

I added a hello world with tracing example.
You can see the readme here: https://github.com/sduskis/cloud-bigtable-examples/tree/add_tracing_hello_world/java/tracing-hello-world

Add tracing hello world

---

java/hello-world/README.md
java/tracing-hello-world/README.md
node/cloud-functions/README.md
node/hello-world/README.md

Update instructions to delete resources provisioned for examples to refer to
instances instead of clusters, including URLs to the Cloud Console and
screenshots of the confirmation dialog.
Fixes #274.

Replace "cluster" with "instance" [skip ci]

---

java/hello-world/pom.xml
java/pom.xml
java/tracing-hello-world/pom.xml

I'm turning off shared-configuration.  I always get "Failed during checkstyle configuration: SuppressionCommentFilter is not allowed as a child in Checker" which is something that I don't know how to fix.  It something wrong in shared-configuration.

Updating hello world to 1.5.0

---

java/tracing-hello-world/README.md

fixes #294 
added stackdriver with link to cost to the `Cost` section
added bigtable link to cost to the `Cost` section

Bigtable: Fix #294 add stackdriver costing info

---

java/tracing-hello-world/pom.xml
java/tracing-hello-world/src/main/java/com/example/cloud/bigtable/helloworld/HelloWorld.java

* Updated dependenicies to latest available versions
* Changed `RpcViews.registerAllViews()` to `RpcViews.registerAllGrpcViews()` as former is deprecated.
* Added `System.exit(0)` as Http-server was preventing it from auto shutdown.

Updated Tracing example with latest dependencies

---

go/connection-refresh/README.md
go/connection-refresh/btrefresh/bigtable_rotator.go
go/connection-refresh/example_program.go

Add an example of how a user could automatically refresh their Cloud Bigtable connections without hitting the automatic connection reset.

Add connection refresh example

---

java/dataflow-connector-examples/README.md
java/dataflow-connector-examples/src/main/java/com/google/cloud/bigtable/dataflow/example/BigQueryBigtableTransfer.java

- Added a note in BigQueryBigtableTransfer.java as discussed on CBT#1919.
- Format the command in a better readable format.

Added a note for Bigtable limitation of 100K columns per Put

---

scala/spark-wordcount/pom.xml
scala/spark-wordcount/src/main/scala/com/example/bigtable/spark/wordcount/WordCount.scala
scala/spark-wordcount/src/test/scala/com/example/bigtable/spark/wordcount/SparkSpec.scala
scala/spark-wordcount/src/test/scala/com/example/bigtable/spark/wordcount/WordCountIT.scala

- Use the latest versions of Bigtable and HBase for 1.x release line matching Dataproc's
- Spark 2.4.5 (Scala 2.11)
- Code cleanup for better readability (hopefully)
Changes tested with [Cloud Bigtable Emulator](https://cloud.google.com/bigtable/docs/emulator) and using `mvn test -DskipTests=false`

[spark-wordcount] Update versions and code (RDD)

---

.github/CODEOWNERS
renovate.json

Fixes #355 
Note: renovate will be turned off to not flood the incoming upgrades

chore: add renovate config and CODEOWNERS file

---

java/metric-scaler/src/main/java/com/example/bigtable/scaler/MetricScaler.java

Matches existing region tags for Python, enables association with Bigtable in snippet tracking by adding product prefix. Will send a CL updating documentation and a second PR removing the obsolete region tags.

chore: normalizing region tags to use product prefix

---

java/metric-scaler/src/main/java/com/example/bigtable/scaler/MetricScaler.java

cl/490048498 removed usage in documentation; this can be merged once `snippet-bot` is happy (since that means the changes will have been successfully published/indexed).

chore: remove obsolete region tags
