- python/rest/README.md
- python/thrift/README.md
I think it's worth adding this note given we both ran into this problem.
> Add Note About Unknown Host Exception

- python/thrift/README.md
- python/thrift/client.py
- python/thrift/flask_thrift.py
- python/thrift/package.sh
I merged a PR to add a command line option parser, but it was broken so I'm just reverting for now so that the code works. Also fixes my package script.
> Revert Options, 

- quickstart/create-hbase-site
Looks at user info and writes the hbase-site.xml file
> Add create-hbase-site

- README.md
Get rid of 0.1.5 reference.
@hegemonic FYI
> Update the Readme to have most of our projects

- java/simple-cli/README.md
- java/simple-cli/pom.xml
- java/simple-cli/src/main/java/com/example/bigtable/simplecli/HBaseCLI.java
- java/simple-cli/src/main/resources/hbase-site.xml
- java/storm/src/main/resources/hbase-site.xml
1. fix pom
2. fix bug in create table
a. Doesn’t accept colFamilies
b. Wrong args to subList
3. reform HBase-site slightly
> Update HBaseCLI to 0.1.9 artifact from Jar

- java/managed-vms/README.md
- java/managed-vms/bigtable-hello/pom.xml
1. Change to use shaded jar
2. Fix ReadMe in many areas.
> Use shaded jar

- quickstart/Dockerfile
- quickstart/create-hbase-site
> Update the QuickStart for 0.1.9

- java/wordcount-mapreduce/README.md
- python/rest/README.md
- python/thrift/README.md
I think I've also simplified the instructions a bit.  Or at least made it so that I won't make the same errors again.
@IanLewis PTAL
@hegemonic PTAL
@waprin FYI
> Deprecate our fork of base as the patches have finally made it.

- java/jetty-managed-vm/README.md
- java/jetty-managed-vm/bigtable-hello/Dockerfile
- java/jetty-managed-vm/bigtable-hello/src/main/java/com.example.cloud.bigtable.helloworld/BigtableHelper.java
- java/jetty-managed-vm/bigtable-hello/src/main/webapp/index.html
- java/managed-vm-gae/README.md
- java/managed-vm-gae/gae-bigtable-hello/Dockerfile
- java/managed-vm-gae/gae-bigtable-hello/src/main/java/com.example.cloud.bigtable.helloworld/BigtableHelper.java
> Use ENV in Dockerfile where possible

- java/managed-vm-gae/README.md
> Warn about gcloud update

- java/jetty-managed-vm/pom.xml
- java/managed-vm-gae/pom.xml
1. Update to 1.1.1 of HBase
2. Specifically call out the hbase-client
@hegemonic FYI
> Update to 1.1.1 of HBase

- quickstart/Dockerfile
- quickstart/create-hbase-site
> QuickStart update to 0.2.0

- java/dataflow-pardo-helloworld/README.md
- java/dataflow-pardo-helloworld/pom.xml
- java/dataflow-pardo-helloworld/src/main/java/com/example/bigtable/dataflow/pardo/HelloWorldBigtablePardo.java
This runs with the current release of CBT, and does not require the upcoming release of CBT.
> Add an example Hello World Bigtable Dataflow app that writes to CBT

- java/dataflow-pardo-helloworld/README.md
@sduskis please review
@hegemonic please review
> Update the readme

- java/dataflow-connector-examples/README.md
- java/dataflow-connector-examples/pom.xml
- java/dataflow-connector-examples/src/main/java/com/google/cloud/bigtable/dataflow/example/HelloWorldWrite.java
- java/dataflow-connector-examples/src/main/java/com/google/cloud/bigtable/dataflow/example/PubsubWordCount.java
- java/dataflow-connector-examples/src/main/java/com/google/cloud/bigtable/dataflow/example/SourceRowCount.java
The README.md needs a bit of work.
We should also setup the pom.xml to properly configure exec:exec for the three examples... perhaps a profile per example?
Feel free to hold off on the review and merge, or to do it and change things appropriately
> Adding examples of the new Cloud Bigtable+Dataflow integration.

- java/dataflow-pardo-helloworld/README.md
> Mention the problem at exit time

- java/dataflow-connector-examples/README.md
> Mention long running job #89

- java/dataflow-connector-examples/pom.xml
Auto switch ALPN version based on JDK version.
> Auto switch ALPN version based on JDK version.

- java/wordcount-mapreduce/dp-mr-hb-init.sh
1. use official name
2. strike some unused lines
> fix attributes

- java/managed-vm-gae/README.md
- java/managed-vm-gae/pom.xml
- java/managed-vm-gae/src/main/webapp/Dockerfile
- java/managed-vm-gae/src/main/webapp/WEB-INF/appengine-web.xml
1. switch to the correct image
2. various cleanups
> Switch to correct image

- java/managed-vm-gae/src/main/webapp/WEB-INF/logging.properties
- java/managed-vm-gae/src/main/webapp/WEB-INF/web.xml
- quickstart/pom.xml
1. Increase quick start back to 512m
2. add a couple of license’s.
> Increase QS Memory back to 512m

- java/hello-world/README.md
- java/hello-world/pom.xml
- java/hello-world/src/main/java/com/example/cloud/bigtable/helloworld/HelloWorld.java
Resubmitting hello world app with profile activation in pom.xml.
> Add a simple java Hello World application using HBase API

- java/hello-world/README.md
- java/hello-world/pom.xml
- java/hello-world/src/main/java/com/example/cloud/bigtable/helloworld/HelloWorld.java
- Go back to using plugin to detect os
- Remove unnecessary maven config for packaging
- Use system properties for project/zone/cluster for consistency
with other examples.
- Only require java 1.7 - works on cloud shell with java 1.7 installed
> Further simplify java Hello World

- java/wordcount-mapreduce/README.md
FYI, this is the guide I followed during a recent PM hackathon, so I was looking at this specific README in-depth. :-)
> Fixed spelling, grammar, spacing, formatting.

- java/dataflow-coinbase/dataflow/pom.xml
- java/dataflow-coinbase/pom.xml
- java/dataflow-connector-examples/pom.xml
- java/dataflow-pardo-helloworld/pom.xml
- java/simple-cli/pom.xml
- java/wordcount-mapreduce/cluster.sh
- java/wordcount-mapreduce/pom.xml
also remove beta from Dataproc script.
> Update to 0.2.3 client

- java-repo-tools/.gitignore
- java-repo-tools/.travis.yml
- java-repo-tools/CONTRIBUTING.md
- java-repo-tools/LICENSE
- java-repo-tools/README.md
- java-repo-tools/google-checks.xml
- java-repo-tools/pom.xml
- java-repo-tools/suppressions.xml
- java-repo-tools/test-devserver.sh
- java-repo-tools/test/README.md
- java-repo-tools/test/pom.xml
- java-repo-tools/test/src/main/java/com/google/cloud/samples/test/App.java
- java-repo-tools/test/src/test/java/com/google/cloud/samples/test/AppTest.java
- java/dataflow-coinbase/dataflow/src/main/java/com/google/cloud/examples/coinflow/data/Schema.java
- java/dataflow-coinbase/dataflow/src/main/java/com/google/cloud/examples/coinflow/sources/CoinbaseSocket.java
- java/dataflow-coinbase/dataflow/src/main/java/com/google/cloud/examples/coinflow/sources/CoinbaseSource.java
- java/dataflow-coinbase/dataflow/src/main/java/com/google/cloud/examples/coinflow/utils/DateHelpers.java
- java/dataflow-coinbase/dataflow/src/test/java/com/google/cloud/examples/coinflow/sources/CoinbaseSourceTest.java
- java/dataflow-coinbase/dataflow/src/test/java/com/google/cloud/examples/coinflow/utils/DataHelpersTest.java
- java/dataflow-coinbase/frontend/src/main/java/com/google/cloud/examples/coinflow/frontend/BigtableHelper.java
- java/dataflow-coinbase/frontend/src/main/java/com/google/cloud/examples/coinflow/frontend/CoinflowServlet.java
- java/dataflow-coinbase/pom.xml
I use the `git subtree` command to pull the history from https://github.com/GoogleCloudPlatform/java-repo-tools so that pulling changes from upstream will be easier.
I only configured the `java/dataflow-coinbase` sample as an example of using this shared configuration, since the samples will require fixes to follow the shared checkstyle configuration.
> Use java repo tools.

- python/thrift/appengine-ssl-gateway/README.md
- python/thrift/appengine-ssl-gateway/appengine/bigtable.py
- python/thrift/appengine-ssl-gateway/appengine/requirements.txt
- python/thrift/appengine-ssl-gateway/appengine/web/index.jinja
- python/thrift/appengine-ssl-gateway/thrift-gateway/Makefile
Tested manually. Was able to get everything built and deployed, though
haven't yet been able to 100% complete the steps in the README.
> Fix flake8 errors in Python Thrift App Engine SSL Gateway sample.

- .travis.yml
- python/.gitignore
- python/nox.py
- travis.sh
There don't appear to be any unit tests yet, but when we do add them they should run too.
> Add Python linting to Travis config.

- quickstart/pom.xml
- quickstart/quickstart.sh
- quickstart/src/main/resources/hbase-site.xml
Update the versions to match (1.2)
> Fix b/28703929 - mixed HBase 1.1 & base 1.2 usage

- README.md
> GoLang -> Go

- java/simple-performance-test/README.md
> change to mention instances instead of clusters

- README.md
Match badges in the `cloud-bigtable-client` repo (Maven not needed here).
> Remove ghit badge, add Travis CI badge.

- README.md
- python/README.md
Fixes https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/issues/197.
> Link to python-docs-samples in README.

- java/dataflow-load-books/pom.xml
- java/dataflow-load-books/src/test/java/com/example/bigtable/loadbooks/LoadBooksIT.java
This should fix your classpath and import issues.
> Attempting to fix configuration of loadbooks.

- java/gae-flexible-helloworld/README.md
- java/gae-flexible-helloworld/pom.xml
- java/gae-flexible-helloworld/src/main/appengine/app.yaml
- java/gae-flexible-helloworld/src/main/java/com/example/bigtable/BigtableHelloWorld.java
- java/gae-flexible-helloworld/src/main/java/com/example/bigtable/BigtableHelper.java
- java/gae-flexible-helloworld/src/main/webapp/WEB-INF/web.xml
- java/gae-flexible-helloworld/src/main/webapp/index.jsp
- java/gae-flexible-helloworld/src/test/java/com/example/bigtable/ITBigtableHelloWorld.java
- java/pom.xml
1. surefire -> failsafe
2. Use parent pom
3. Lots of checkstyle improvements
4. Better readme
5. Remove Test from Integration Test
> Fixes for Tim

- java/dataflow-load-books/README.md
- java/dataflow-load-books/src/test/java/com/example/bigtable/loadbooks/LoadBooksIT.java
> Use books table instead of helloworld for books sample.

- java/gae-flexible-helloworld/pom.xml
- java/gae-flexible-helloworld/src/main/appengine/app.yaml
- java/gae-flexible-helloworld/src/main/java/com/example/bigtable/BigtableHelloWorld.java
- java/gae-flexible-helloworld/src/main/java/com/example/bigtable/BigtableHelper.java
1. Didn’t compile - fixed. (Not sure how that’s possible)
2. Add @Override in the right place
> Fixups for flexible-hello

- README.md
@lesv FYI: I'll merge right away since it's just a link update in the README.
Closes #222.
> Fix links to Go samples.

- README.md
- java/dataflow-connector-examples/README.md
- java/dataflow-connector-examples/pom.xml
- java/dataflow-connector-examples/src/main/java/com/google/cloud/bigtable/dataflow/example/BigQueryBigtableTransfer.java
an example showing how to read records from BigQuery and write them to BigTable
> BigQueryBigtableTransfer

- java/dataflow-coinbase/dataflow/pom.xml
- java/dataflow-coinbase/frontend/pom.xml
- java/dataflow-coinbase/pom.xml
- java/dataflow-connector-examples/pom.xml
- java/dataflow-load-books/pom.xml
- java/dataproc-wordcount/pom.xml
- java/gae-flexible-helloworld/pom.xml
- java/hello-world/pom.xml
- java/simple-cli/pom.xml
Also switching to bigtable-hbase-1.x.
This PR does not include an upgrade of simple-performance-test, since I hit some snags with it.  This PR will work towards #235.
> Upgrading to Cloud Bigtable 1.0.0-pre1

- quickstart/pom.xml
- quickstart/quickstart.sh
1. update to 1.0.0-pre3
2. revert gcloud usage to beta again.
> update to pre3

- java/dataproc-wordcount/pom.xml
- java/dataproc-wordcount/src/main/resources/hbase-site.xml
- java/hello-world/pom.xml
- java/simple-cli/pom.xml
- java/simple-cli/src/main/resources/hbase-site.xml
I updated to the bigtable-hbase-1.x artifact Id, but did not update hbase-site.xml correctly, as per issue #251.  This PR fixes that problem.  Also, remove tcnative and hbase-client where possible.
@lesv, @igorbernstein2, FYI
> Fixing a problem with wrong connection strings

- scala/bigtable-shc/README.md
- scala/spark-streaming/README.md
- scala/spark-streaming/pom.xml
- scala/spark-streaming/src/main/scala/com/example/bigtable/spark/wordcount/WordCount.scala
- scala/spark-wordcount/README.md
* Streaming example somehow got lost in the shuffle
* Standardize environment variable and fix some README stuff
> Add Streaming back, add doc touchups

- .gitignore
- .travis.yml
- README.md
- node/.eslintignore
- node/.eslintrc.json
- node/hello-world/README.md
- node/hello-world/index.js
- node/hello-world/index.v4.js
- node/hello-world/package.json
- node/package.json
- travis.sh
This PR includes tests which lint the javascript files to adhere to the [Google Style Guide](https://github.com/google/eslint-config-google) rules and to ensure that the TOC in the README files are up to date.
> Add a simple nodejs Hello World example using the nodejs client library.

- scala/bigtable-shc/README.md
- scala/bigtable-shc/src/main/scala/com/example/bigtable/spark/shc/AgeSource.scala
`BigtableSource` is closer to the example `shc` repo provides, but it's a bit abstract. I put together this sample for the demo, and figured it probably wouldn't hurt to add it here.
> Add AgeSource example

- java/dataflow-coinbase/pom.xml
- java/dataflow-connector-examples/pom.xml
- java/dataflow-load-books/pom.xml
- java/dataproc-wordcount/pom.xml
- java/gae-flexible-helloworld/pom.xml
- java/hello-world/pom.xml
- java/metric-scaler/pom.xml
- java/simple-cli/pom.xml
- java/simple-performance-test/pom.xml
- quickstart/pom.xml
- scala/bigtable-shc/pom.xml
- scala/spark-streaming/pom.xml
- scala/spark-wordcount/pom.xml
> Upgrading dependencies to bigtable-hbase 1.0.0

- java/tracing-hello-world/README.md
- java/tracing-hello-world/pom.xml
- java/tracing-hello-world/src/main/java/com/example/cloud/bigtable/helloworld/HelloWorld.java
- Upgrading to the 1.3.0 client
- Adding stats export
- Adding links to opencensus.io
> Updating the tracing hello world.

- quickstart/quickstart.sh
this allows you to do `./cloud-bigtable-examples/quickstarts/quickstart.sh`
> Allow executing from any directory

- java/dataflow-connector-examples/pom.xml
- java/dataflow-connector-examples/src/main/java/com/google/cloud/bigtable/dataflow/example/CsvImport.java
- travis.sh
Adding additional arguments for CSV import allowing users to specify
region
network
subnetwork
service account
public ips
As well as adding validation for some existing parameters
> Adding additional arguments for CSV import and some validation

- scala/bigtable-shc/README.md
- scala/bigtable-shc/pom.xml
- scala/bigtable-shc/src/main/resources/hbase-site.xml
- scala/bigtable-shc/src/main/scala/com/example/bigtable/spark/shc/AgeSource.scala
- scala/bigtable-shc/src/main/scala/com/example/bigtable/spark/shc/BigtableSource.scala
* Google Cloud Bigtable 1.8.0 (hbase2_x)
* Apache Spark 2.4.0
* Apache Spark - Apache HBase Connector 1.1.3-2.4
/cc @sduskis
> Update the SHC example to the latest versions

- java/quickstart/pom.xml
- java/quickstart/src/main/java/com/example/cloud/bigtable/quickstart/Quickstart.java
- java/quickstart/src/test/java/com/example/cloud/bigtable/quickstart/it/QuickstartIT.java
* Updated `bigtable-hbase-1.x` to 1.9.0.
* Added more formatted terminal comments.
* Standardized `projectID` argument for Integration Test.
> Upgraded quickstart-example with hbase-1.9.0 version.

- scala/spark-wordcount/pom.xml
- scala/spark-wordcount/src/main/scala/com/example/bigtable/spark/wordcount/WordCount.scala
Creating this PR as a workaround for this issue:
https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/issues/279
> Issue# 279

- java/hello-world/src/main/java/com/example/cloud/bigtable/helloworld/HelloWorld.java
Fix compilation issues introduced in https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/pull/331
> Fix table clean up

- java/metric-scaler/README.md
- java/metric-scaler/pom.xml
- java/metric-scaler/src/main/java/com/example/bigtable/scaler/MetricScaler.java
- java/metric-scaler/src/main/resources/log4j.properties
- java/pom.xml
Reverts GoogleCloudPlatform/cloud-bigtable-examples#369
> Revert "chore: remove unused metric scaler examples"

- java/pom.xml
- java/quickstart/pom.xml
Stacked PRs:
* #403
* #402
* #401
* #400
* #399
* __->__#398
--- --- ---
> chore:  fix poms and get the repo building again
